name: Vercel Cron Job

on:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Review Radar API
        run: |
          curl -X GET "https://review-radar.vercel.app/api/place-reviews"
